name: Publish release to GitHub
description: Publish the target version to GitHub.

inputs:
  version:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Download distribution artifacts
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
      with:
        name: dist-${{ inputs.version }}
        path: dist-${{ inputs.version }}/

    - name: Sign the artifacts with Sigstore
      uses: sigstore/gh-action-sigstore-python@f514d46b907ebcd5bedc05145c03b69c1edd8b46 # v3.0.0
      with:
        inputs: ./dist-${{ inputs.version }}/*.tar.gz ./dist-${{ inputs.version }}/*.whl

    - name: Create GitHub release
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        VERSION: ${{ inputs.version }}
      run: |
        args=()
        if [[ "$VERSION" == *rc* ]]; then
          args+=(--prerelease)
        fi
        gh release create "$VERSION" --verify-tag \
          --repo "${{ github.repository }}" \
          --generate-notes \
          "${args[@]}"

    - name: Upload artifact signatures to GitHub release
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        VERSION: ${{ inputs.version }}
      run: gh release upload "$VERSION" dist-"${VERSION}"/** --repo "${{ github.repository }}"
