name: Publish release
description: Tag, build, and publish a release or release-candidate on PR merge.

on:
  pull_request:
    branches:
      - master
      - release
    types:
      - closed
    paths:
      - src/**
      - pyproject.toml

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    permissions:
      contents: write
    outputs:
      version: ${{ steps.bump-version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          token: ${{ secrets.MY_TOKEN }}
          ref: ${{ github.head_ref }}
      - name: Determine version segment to bump
        id: determine-version-segment
        env:
          BASE_REF: ${{ github.base_ref }}
          HEAD_REF: ${{ github.head_ref }}
        run: |
          case "$BASE_REF" in
            master)
              case "$HEAD_REF" in
                release)
                  echo "segment=minor" >> $GITHUB_OUTPUT
                  ;;
                *)
                  echo "segment=patch" >> $GITHUB_OUTPUT
                  ;;
              esac
              ;;
            release)
              echo "segment=patch" >> $GITHUB_OUTPUT
              ;;
            *)
              echo "Error: Unsupported base branch $BASE_REF" >&2
              exit 1
              ;;
          esac
      - name: Bump version
        id: bump-version
        run: |
          git fetch --unshallow
          old_version=$(git describe --tags $(git rev-list --tags --max-count=1))
          new_version=$(.github/scripts/bump-version.sh ${{ steps.determine-version-segment.outputs.segment }} $old_version)
          echo "Bumping $old_version to $new_version"
          echo "version=$new_version" >> $GITHUB_OUTPUT

  tag-version:
    name: Tag version
    needs: bump-version
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          token: ${{ secrets.MY_TOKEN }}
      - name: Create tag
        id: create-tag
        env:
          NEW_VERSION: ${{ needs.bump-version.outputs.version }}
        run: |
          echo "Tagging $NEW_VERSION"
          git tag "$NEW_VERSION"
          git push origin "$NEW_VERSION"
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

  build-release:
    name: Build release
    needs:
      - bump-version
      - tag-version
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - uses: ./.github/actions/build-release
        with:
          version: ${{ needs.bump-version.outputs.version }}

  publish-github-release:
    name: Publish release to GitHub
    needs:
      - bump-version
      - tag-version
      - build-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - uses: ./.github/actions/publish-github-release
        with:
          version: ${{ needs.bump-version.outputs.version }}

  publish-pypi-release:
    name: Publish release to PyPI
    needs:
      - bump-version
      - tag-version
      - build-release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - uses: ./.github/actions/publish-pypi-release
        with:
          version: ${{ needs.bump-version.outputs.version }}
          pypi-token: ${{ secrets.PYPI_TOKEN }}

  drop-release:
    name: Drop release
    needs:
      - build-release
      - publish-github-release
      - publish-pypi-release
    runs-on: ubuntu-latest
    if: always() && !contains(needs.*.result, 'failure') && github.event.pull_request.merged == true && github.head_ref == 'release' && github.base_ref == 'master'
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          token: ${{ secrets.MY_TOKEN }}
      - name: Drop release branch
        run: |
          git fetch --unshallow
          if [[ -n $(git ls-remote --heads origin release) ]]; then
            git push origin --delete release
          else
            echo "Release branch not found, skipping."
          fi
